; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26730.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\levent\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
