.TH "Actor::Factory" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Actor::Factory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Actor_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSprite::Factory\fP * \fBsprites\fP"
.br
.ti -1c
.RI "int \fBn_sprites\fP"
.br
.ti -1c
.RI "int \fBsprite_array_size\fP"
.br
.ti -1c
.RI "\fBBody::Factory\fP \fBbodies\fP"
.br
.ti -1c
.RI "\fBShape::Rect::Factory\fP \fBworld_coords\fP"
.br
.ti -1c
.RI "int * \fBcurrent_sprite\fP"
.br
.ti -1c
.RI "int * \fBstate\fP"
.br
.ti -1c
.RI "unsigned int * \fBcreation_time\fP"
.br
.ti -1c
.RI "\fBRGBA::RGBA\fP * \fBcolor\fP"
.br
.ti -1c
.RI "int * \fBsprite_flip\fP"
.br
.ti -1c
.RI "int \fBarray_size\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Actor::Factory::array_size"

.SS "\fBBody::Factory\fP Actor::Factory::bodies"

.SS "\fBRGBA::RGBA\fP* Actor::Factory::color"

.SS "unsigned int* Actor::Factory::creation_time"

.SS "int* Actor::Factory::current_sprite"

.SS "int Actor::Factory::n_sprites"

.SS "int Actor::Factory::sprite_array_size"

.SS "int* Actor::Factory::sprite_flip"

.SS "\fBSprite::Factory\fP* Actor::Factory::sprites"

.SS "int* Actor::Factory::state"

.SS "\fBShape::Rect::Factory\fP Actor::Factory::world_coords"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
