.TH "Actor::internal" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Actor::internal
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBresize_Sprites\fP (\fBFactory\fP *f)"
.br
.ti -1c
.RI "int \fBfind_New\fP (\fBFactory\fP *f)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int Actor::internal::find_New (\fBFactory\fP * f)"

.SS "void Actor::internal::resize_Sprites (\fBFactory\fP * f)"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
