.TH "Audio" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Audio
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (int buffer_size)"
.br
.ti -1c
.RI "int \fBadd_Music\fP (const char *music_filename)"
.br
.ti -1c
.RI "void \fBplay_Music\fP (int index, int loop)"
.br
.ti -1c
.RI "void \fBpause_Music\fP ()"
.br
.ti -1c
.RI "void \fBresume_Music\fP ()"
.br
.ti -1c
.RI "int \fBadd_FX\fP (const char *fx_filename)"
.br
.ti -1c
.RI "int \fBset_FX_Volume\fP (int index, int volume)"
.br
.ti -1c
.RI "int \fBset_Music_Volume\fP (int volume)"
.br
.ti -1c
.RI "void \fBplay_FX\fP (unsigned char index)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBn_sounds\fP = 0"
.br
.ti -1c
.RI "const int \fBmax_n_sounds\fP = 256"
.br
.ti -1c
.RI "const int \fBn_channel_per_sound\fP = 4"
.br
.ti -1c
.RI "Mix_Chunk * \fBsound_fx\fP [\fBmax_n_sounds\fP *\fBn_channel_per_sound\fP]"
.br
.ti -1c
.RI "int \fBring\fP [\fBmax_n_sounds\fP]"
.br
.ti -1c
.RI "int \fBn_music\fP = 0"
.br
.ti -1c
.RI "const int \fBmax_n_music\fP = 256"
.br
.ti -1c
.RI "Mix_Music * \fBmusic\fP [\fBmax_n_music\fP]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int Audio::add_FX (const char * fx_filename)"

.SS "int Audio::add_Music (const char * music_filename)"

.SS "void Audio::init (int buffer_size)"

.SS "void Audio::pause_Music ()"

.SS "void Audio::play_FX (unsigned char index)"

.SS "void Audio::play_Music (int index, int loop)"

.SS "void Audio::resume_Music ()"

.SS "int Audio::set_FX_Volume (int index, int volume)"

.SS "int Audio::set_Music_Volume (int volume)"

.SH "Variable Documentation"
.PP 
.SS "const int Audio::max_n_music = 256"

.SS "const int Audio::max_n_sounds = 256"

.SS "Mix_Music* Audio::music[\fBmax_n_music\fP]"

.SS "const int Audio::n_channel_per_sound = 4"

.SS "int Audio::n_music = 0"

.SS "int Audio::n_sounds = 0"

.SS "int Audio::ring[\fBmax_n_sounds\fP]"

.SS "Mix_Chunk* Audio::sound_fx[\fBmax_n_sounds\fP *\fBn_channel_per_sound\fP]"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
