.TH "include/Audio_core.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Audio_core.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL2\-2\&.0\&.8\\include\\SDL_mixer\&.h'\fP
.br
\fC#include 'Audio_data\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAudio\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAudio::init\fP (int buffer_size)"
.br
.ti -1c
.RI "int \fBAudio::add_Music\fP (const char *music_filename)"
.br
.ti -1c
.RI "void \fBAudio::play_Music\fP (int index, int loop)"
.br
.ti -1c
.RI "void \fBAudio::pause_Music\fP ()"
.br
.ti -1c
.RI "void \fBAudio::resume_Music\fP ()"
.br
.ti -1c
.RI "int \fBAudio::add_FX\fP (const char *fx_filename)"
.br
.ti -1c
.RI "int \fBAudio::set_FX_Volume\fP (int index, int volume)"
.br
.ti -1c
.RI "int \fBAudio::set_Music_Volume\fP (int volume)"
.br
.ti -1c
.RI "void \fBAudio::play_FX\fP (unsigned char index)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
