.TH "Body::Factory" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Body::Factory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Body_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBn_bodies\fP"
.br
.ti -1c
.RI "int \fBarray_size\fP"
.br
.ti -1c
.RI "\fBVec2D::Vec2D\fP * \fBforce\fP"
.br
.ti -1c
.RI "\fBVec2D::Vec2D\fP * \fBpos\fP"
.br
.ti -1c
.RI "\fBVec2D::Vec2D\fP * \fBlast_pos\fP"
.br
.ti -1c
.RI "\fBVec2D::Vec2D\fP * \fBvel\fP"
.br
.ti -1c
.RI "float * \fBmass\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Body::Factory::array_size"

.SS "\fBVec2D::Vec2D\fP* Body::Factory::force"

.SS "\fBVec2D::Vec2D\fP* Body::Factory::last_pos"

.SS "float* Body::Factory::mass"

.SS "int Body::Factory::n_bodies"

.SS "\fBVec2D::Vec2D\fP* Body::Factory::pos"

.SS "\fBVec2D::Vec2D\fP* Body::Factory::vel"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
