.TH "include/Collision_core.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Collision_core.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Collision_data\&.h'\fP
.br
\fC#include 'Shape_core\&.h'\fP
.br
\fC#include 'Grid_core\&.h'\fP
.br
\fC#include 'Vec_core\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCollision\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBCollision::box\fP (\fBShape::Rect::Data\fP *out, const \fBShape::Rect::Data\fP *in, float shrink)"
.br
.ti -1c
.RI "void \fBCollision::point_Feeler_Pos\fP (Point_Feeler *p, const \fBShape::Rect::Data\fP *r, float t_margin, float x_margin)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
