.TH "Collision::Point_Feeler" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collision::Point_Feeler
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Collision_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVec2D::Vec2D\fP \fBbottom_feeler\fP"
.br
.ti -1c
.RI "\fBVec2D::Vec2D\fP \fBtop_feeler\fP"
.br
.ti -1c
.RI "\fBVec2D::Vec2D\fP \fBleft_feeler\fP"
.br
.ti -1c
.RI "\fBVec2D::Vec2D\fP \fBright_feeler\fP"
.br
.ti -1c
.RI "\fBVec2D::Vec2D\fP \fBmid_feeler\fP"
.br
.ti -1c
.RI "\fBVec2D::Vec2D\fP \fBtopleft_feeler\fP"
.br
.ti -1c
.RI "\fBVec2D::Vec2D\fP \fBtopright_feeler\fP"
.br
.ti -1c
.RI "\fBVec2D::Vec2D\fP \fBbottomleft_feeler\fP"
.br
.ti -1c
.RI "\fBVec2D::Vec2D\fP \fBbottomright_feeler\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBVec2D::Vec2D\fP Collision::Point_Feeler::bottom_feeler"

.SS "\fBVec2D::Vec2D\fP Collision::Point_Feeler::bottomleft_feeler"

.SS "\fBVec2D::Vec2D\fP Collision::Point_Feeler::bottomright_feeler"

.SS "\fBVec2D::Vec2D\fP Collision::Point_Feeler::left_feeler"

.SS "\fBVec2D::Vec2D\fP Collision::Point_Feeler::mid_feeler"

.SS "\fBVec2D::Vec2D\fP Collision::Point_Feeler::right_feeler"

.SS "\fBVec2D::Vec2D\fP Collision::Point_Feeler::top_feeler"

.SS "\fBVec2D::Vec2D\fP Collision::Point_Feeler::topleft_feeler"

.SS "\fBVec2D::Vec2D\fP Collision::Point_Feeler::topright_feeler"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
