.TH "Collision" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collision
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPoint_Feeler\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbox\fP (\fBShape::Rect::Data\fP *out, const \fBShape::Rect::Data\fP *in, float shrink)"
.br
.ti -1c
.RI "void \fBpoint_Feeler_Pos\fP (\fBPoint_Feeler\fP *p, const \fBShape::Rect::Data\fP *r, float t_margin, float x_margin)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Collision::box (\fBShape::Rect::Data\fP * out, const \fBShape::Rect::Data\fP * in, float shrink)"

.SS "void Collision::point_Feeler_Pos (\fBPoint_Feeler\fP * p, const \fBShape::Rect::Data\fP * r, float t_margin, float x_margin)"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
