.TH "Engine" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Engine
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBtime\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP (const char *window_title, int _screen_width, int _screen_height)"
.br
.ti -1c
.RI "void \fBevent_Loop\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SDL_Renderer * \fBrenderer\fP = NULL"
.br
.ti -1c
.RI "SDL_Window * \fBwindow\fP = NULL"
.br
.ti -1c
.RI "int \fBscreen_width\fP"
.br
.ti -1c
.RI "int \fBscreen_height\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Engine::event_Loop ()"

.SS "void Engine::init (const char * window_title, int _screen_width, int _screen_height)"

.SS "unsigned int Engine::time ()"

.SH "Variable Documentation"
.PP 
.SS "SDL_Renderer* Engine::renderer = NULL"

.SS "int Engine::screen_height"

.SS "int Engine::screen_width"

.SS "SDL_Window* Engine::window = NULL"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
