.TH "include/Engine_data.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Engine_data.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL2\-2\&.0\&.8/include/SDL\&.h'\fP
.br
\fC#include 'Tileset_data\&.h'\fP
.br
\fC#include 'Sprite_data\&.h'\fP
.br
\fC#include 'Grid_Camera_core\&.h'\fP
.br
\fC#include 'Actor_data\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBEngine\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "SDL_Renderer * \fBEngine::renderer\fP = NULL"
.br
.ti -1c
.RI "SDL_Window * \fBEngine::window\fP = NULL"
.br
.ti -1c
.RI "int \fBEngine::screen_width\fP"
.br
.ti -1c
.RI "int \fBEngine::screen_height\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
