.TH "Font" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Font
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFont\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (\fBFont\fP *f, const char *font_image_filename, const SDL_Renderer *renderer)"
.br
.ti -1c
.RI "void \fBset_Screen_Pos\fP (\fBFont\fP *f, float x, float y)"
.br
.ti -1c
.RI "void \fBset_Screen_Size\fP (\fBFont\fP *f, float w, float h)"
.br
.ti -1c
.RI "void \fBdraw\fP (\fBFont\fP *f, const char *str, int length, const \fBGrid_Camera::Grid_Camera\fP *c, const SDL_Renderer *renderer)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Font::draw (\fBFont\fP * f, const char * str, int length, const \fBGrid_Camera::Grid_Camera\fP * c, const SDL_Renderer * renderer)"

.SS "void Font::init (\fBFont\fP * f, const char * font_image_filename, const SDL_Renderer * renderer)"

.SS "void Font::set_Screen_Pos (\fBFont\fP * f, float x, float y)"

.SS "void Font::set_Screen_Size (\fBFont\fP * f, float w, float h)"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
