.TH "Font::Font" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Font::Font
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Font_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBShape::Rect::Data\fP \fBscreen_coord\fP"
.br
.ti -1c
.RI "\fBTileset::Tileset\fP \fBtileset\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBShape::Rect::Data\fP Font::Font::screen_coord"

.SS "\fBTileset::Tileset\fP Font::Font::tileset"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
