.TH "Grid::Region" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Grid::Region
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Grid_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx0\fP"
.br
.ti -1c
.RI "int \fBy0\fP"
.br
.ti -1c
.RI "int \fBx1\fP"
.br
.ti -1c
.RI "int \fBy1\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Grid::Region::x0"

.SS "int Grid::Region::x1"

.SS "int Grid::Region::y0"

.SS "int Grid::Region::y1"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
