.TH "Grid_Camera::Grid_Camera" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Grid_Camera::Grid_Camera
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Grid_Camera_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBShape::Rect::Data\fP \fBworld_coord\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBscreen_width\fP"
.br
.ti -1c
.RI "   int \fBscreen_height\fP"
.br
.ti -1c
.RI "} \fBinit\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBtile_x\fP"
.br
.ti -1c
.RI "   int \fBtile_y\fP"
.br
.ti -1c
.RI "   int \fBtile_w\fP"
.br
.ti -1c
.RI "   int \fBtile_h\fP"
.br
.ti -1c
.RI "} \fBcalibration\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct { \&.\&.\&. }   Grid_Camera::Grid_Camera::calibration"

.SS "struct { \&.\&.\&. }   Grid_Camera::Grid_Camera::init"

.SS "int Grid_Camera::Grid_Camera::screen_height"

.SS "int Grid_Camera::Grid_Camera::screen_width"

.SS "int Grid_Camera::Grid_Camera::tile_h"

.SS "int Grid_Camera::Grid_Camera::tile_w"

.SS "int Grid_Camera::Grid_Camera::tile_x"

.SS "int Grid_Camera::Grid_Camera::tile_y"

.SS "\fBShape::Rect::Data\fP Grid_Camera::Grid_Camera::world_coord"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
