.TH "Grid::Point" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Grid::Point
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Grid_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Grid::Point::x"

.SS "int Grid::Point::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
