.TH "include/Grid_Camera_core.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Grid_Camera_core.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Vec_core\&.h'\fP
.br
\fC#include 'Grid_Camera_data\&.h'\fP
.br
\fC#include 'Grid_core\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBGrid_Camera\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBGrid_Camera::init\fP (Grid_Camera *c, int screen_width, int screen_height)"
.br
.ti -1c
.RI "void \fBGrid_Camera::grid_to_Screen\fP (\fBShape::Rect::Data\fP *screen_coord, const \fBShape::Rect::Data\fP *world_coord, const Grid_Camera *cam)"
.br
.ti -1c
.RI "void \fBGrid_Camera::screen_to_Grid\fP (\fBVec2D::Vec2D\fP *grid_point, \fBVec2D::Vec2D\fP *screen_point, const Grid_Camera *c)"
.br
.ti -1c
.RI "void \fBGrid_Camera::calibrate\fP (Grid_Camera *cam)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
