.TH "include/Input_core.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Input_core.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Input_data\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBInput\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBInput::init\fP ()"
.br
.ti -1c
.RI "void \fBInput::prepare\fP ()"
.br
.ti -1c
.RI "void \fBInput::update\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
