.TH "include/Input_data.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Input_data.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL2\-2\&.0\&.8/include/SDL\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBInput\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned char \fBInput::prev_key_state\fP [256]"
.br
.ti -1c
.RI "unsigned char * \fBInput::keys\fP = NULL"
.br
.ti -1c
.RI "int \fBInput::mouse_x\fP"
.br
.ti -1c
.RI "int \fBInput::mouse_y\fP"
.br
.ti -1c
.RI "int \fBInput::mouse_left\fP"
.br
.ti -1c
.RI "int \fBInput::prev_mouse_left\fP"
.br
.ti -1c
.RI "int \fBInput::mouse_right\fP"
.br
.ti -1c
.RI "int \fBInput::prev_mouse_right\fP"
.br
.ti -1c
.RI "const int \fBInput::max_n_game_controllers\fP = 4"
.br
.ti -1c
.RI "SDL_GameController * \fBInput::game_controller\fP [max_n_game_controllers]"
.br
.ti -1c
.RI "int \fBInput::prev_game_controller_sticks\fP [max_n_game_controllers][6]"
.br
.ti -1c
.RI "int \fBInput::game_controller_sticks\fP [max_n_game_controllers][6]"
.br
.ti -1c
.RI "int \fBInput::prev_game_controller_buttons\fP [max_n_game_controllers][15]"
.br
.ti -1c
.RI "int \fBInput::game_controller_buttons\fP [max_n_game_controllers][15]"
.br
.ti -1c
.RI "int \fBInput::n_game_controllers\fP = 0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
