.TH "Light::Factory" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Light::Factory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Light_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVec2D::Vec2D\fP * \fBpos\fP"
.br
.ti -1c
.RI "float * \fBz_height\fP"
.br
.ti -1c
.RI "float * \fBintensity\fP"
.br
.ti -1c
.RI "\fBRGB::RGB\fP * \fBcolor\fP"
.br
.ti -1c
.RI "int \fBarray_size\fP"
.br
.ti -1c
.RI "int \fBn_lights\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Light::Factory::array_size"

.SS "\fBRGB::RGB\fP* Light::Factory::color"

.SS "float* Light::Factory::intensity"

.SS "int Light::Factory::n_lights"

.SS "\fBVec2D::Vec2D\fP* Light::Factory::pos"

.SS "float* Light::Factory::z_height"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
