.TH "include/Light_data.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Light_data.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Vec_data\&.h'\fP
.br
\fC#include 'RGBA_data\&.h'\fP
.br
\fC#include 'SDL2\-2\&.0\&.8/include/SDL\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLight::Factory\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBLight\fP"
.br
.ti -1c
.RI " \fBLight::internal\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBLight::ambient\fP"
.br
.ti -1c
.RI "SDL_Texture * \fBLight::internal::lightmap\fP"
.br
.ti -1c
.RI "int \fBLight::internal::w\fP"
.br
.ti -1c
.RI "int \fBLight::internal::h\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
