.TH "Light::internal" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Light::internal
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "SDL_Texture * \fBlightmap\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "int Light::internal::h"

.SS "SDL_Texture* Light::internal::lightmap"

.SS "int Light::internal::w"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
