.TH "Light" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Light
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBinternal\fP"
.br
.ti -1c
.RI " \fBSystem\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFactory\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (\fBFactory\fP *f, int array_size)"
.br
.ti -1c
.RI "void \fBresize\fP (\fBFactory\fP *f)"
.br
.ti -1c
.RI "int \fBmake_Instance\fP (\fBFactory\fP *f)"
.br
.ti -1c
.RI "void \fBdraw\fP (\fBFactory\fP *l, \fBGrid_Camera::Grid_Camera\fP *cam, SDL_Renderer *renderer)"
.br
.ti -1c
.RI "void \fBset_Color\fP (int which_light, \fBRGB::RGB\fP *rgb, \fBFactory\fP *l)"
.br
.ti -1c
.RI "void \fBset_Pos\fP (int which_light, \fBVec2D::Vec2D\fP *pos, \fBFactory\fP *l)"
.br
.ti -1c
.RI "void \fBset_Z_Height\fP (int which_light, float z_height, \fBFactory\fP *l)"
.br
.ti -1c
.RI "void \fBset_Intensity\fP (int which_light, float intensity, \fBFactory\fP *l)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBambient\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Light::draw (\fBFactory\fP * l, \fBGrid_Camera::Grid_Camera\fP * cam, SDL_Renderer * renderer)"

.SS "void Light::init (\fBFactory\fP * f, int array_size)"

.SS "int Light::make_Instance (\fBFactory\fP * f)"

.SS "void Light::resize (\fBFactory\fP * f)"

.SS "void Light::set_Color (int which_light, \fBRGB::RGB\fP * rgb, \fBFactory\fP * l)"

.SS "void Light::set_Intensity (int which_light, float intensity, \fBFactory\fP * l)"

.SS "void Light::set_Pos (int which_light, \fBVec2D::Vec2D\fP * pos, \fBFactory\fP * l)"

.SS "void Light::set_Z_Height (int which_light, float z_height, \fBFactory\fP * l)"

.SH "Variable Documentation"
.PP 
.SS "float Light::ambient"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
