.TH "Particle::Emitter" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Particle::Emitter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Particle_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVec2D::Vec2D\fP \fBemitter_world_coords\fP"
.br
.ti -1c
.RI "\fBSprite::Factory\fP \fBsprites\fP"
.br
.ti -1c
.RI "\fBBody::Factory\fP \fBbodies\fP"
.br
.ti -1c
.RI "\fBShape::Rect::Factory\fP \fBworld_coords\fP"
.br
.ti -1c
.RI "int * \fBstate\fP"
.br
.ti -1c
.RI "unsigned int * \fBcreation_time\fP"
.br
.ti -1c
.RI "int * \fBlife_span\fP"
.br
.ti -1c
.RI "int \fBarray_size\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Particle::Emitter::array_size"

.SS "\fBBody::Factory\fP Particle::Emitter::bodies"

.SS "unsigned int* Particle::Emitter::creation_time"

.SS "\fBVec2D::Vec2D\fP Particle::Emitter::emitter_world_coords"

.SS "int* Particle::Emitter::life_span"

.SS "\fBSprite::Factory\fP Particle::Emitter::sprites"

.SS "int* Particle::Emitter::state"

.SS "\fBShape::Rect::Factory\fP Particle::Emitter::world_coords"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
