.TH "RGB" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGB
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRGB\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBRGB::RGB\fP \fBdefault\fP = { 255,255,255 }"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "struct \fBRGB::RGB\fP  RGB::default = { 255,255,255 }"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
