.TH "RGBA::RGBA" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGBA::RGBA
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RGBA_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBr\fP"
.br
.ti -1c
.RI "unsigned char \fBg\fP"
.br
.ti -1c
.RI "unsigned char \fBb\fP"
.br
.ti -1c
.RI "unsigned char \fBa\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned char RGBA::RGBA::a"

.SS "unsigned char RGBA::RGBA::b"

.SS "unsigned char RGBA::RGBA::g"

.SS "unsigned char RGBA::RGBA::r"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
