.TH "RGBA" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGBA
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRGBA\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBRGBA::RGBA\fP \fBdefault\fP = {255,255,255,255}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "struct \fBRGBA::RGBA\fP  RGBA::default = {255,255,255,255}"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
