.TH "include/RGBA_data.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/RGBA_data.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRGBA::RGBA\fP"
.br
.ti -1c
.RI "struct \fBRGB::RGB\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBRGBA\fP"
.br
.ti -1c
.RI " \fBRGB\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBRGBA::RGBA\fP \fBRGBA::default\fP = {255,255,255,255}"
.br
.ti -1c
.RI "struct \fBRGB::RGB\fP \fBRGB::default\fP = { 255,255,255 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
