.TH "Shape::Rect::Data" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shape::Rect::Data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Shape_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float Shape::Rect::Data::h"

.SS "float Shape::Rect::Data::w"

.SS "float Shape::Rect::Data::x"

.SS "float Shape::Rect::Data::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
