.TH "Shape::Rect::Factory" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shape::Rect::Factory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Shape_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBData\fP * \fBrect\fP"
.br
.ti -1c
.RI "int \fBn_rect\fP"
.br
.ti -1c
.RI "int \fBarray_size\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Shape::Rect::Factory::array_size"

.SS "int Shape::Rect::Factory::n_rect"

.SS "\fBData\fP* Shape::Rect::Factory::rect"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
