.TH "Shape::Rect" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shape::Rect
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBData\fP"
.br
.ti -1c
.RI "struct \fBFactory\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (\fBFactory\fP *f, int array_size)"
.br
.ti -1c
.RI "void \fBresize\fP (\fBFactory\fP *f)"
.br
.ti -1c
.RI "int \fBmake_Instance\fP (\fBFactory\fP *f)"
.br
.ti -1c
.RI "int \fBcollision\fP (const \fBData\fP *pa, const \fBRect::Data\fP *pb)"
.br
.ti -1c
.RI "int \fBcollision_with_Dir\fP (const \fBData\fP *a, const \fBRect::Data\fP *b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int Shape::Rect::collision (const \fBData\fP * pa, const \fBRect::Data\fP * pb)"

.SS "int Shape::Rect::collision_with_Dir (const \fBData\fP * a, const \fBRect::Data\fP * b)"

.SS "void Shape::Rect::init (\fBFactory\fP * f, int array_size)"

.SS "int Shape::Rect::make_Instance (\fBFactory\fP * f)"

.SS "void Shape::Rect::resize (\fBFactory\fP * f)"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
