.TH "Sprite::Instance" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sprite::Instance
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBInstance\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (\fBInstance\fP *s, int array_size)"
.br
.ti -1c
.RI "void \fBresize\fP (\fBInstance\fP *s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Sprite::Instance::init (\fBInstance\fP * s, int array_size)"

.SS "void Sprite::Instance::resize (\fBInstance\fP * s)"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
