.TH "Sprite::Instance::Instance" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sprite::Instance::Instance
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sprite_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int * \fBlast_frame_change_time\fP"
.br
.ti -1c
.RI "int * \fBframe_duration\fP"
.br
.ti -1c
.RI "int * \fBcurrent_frame\fP"
.br
.ti -1c
.RI "int \fBn_instances\fP"
.br
.ti -1c
.RI "int \fBarray_size\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Sprite::Instance::Instance::array_size"

.SS "int* Sprite::Instance::Instance::current_frame"

.SS "int* Sprite::Instance::Instance::frame_duration"

.SS "unsigned int* Sprite::Instance::Instance::last_frame_change_time"

.SS "int Sprite::Instance::Instance::n_instances"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
