.TH "Sprite::Factory" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sprite::Factory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sprite_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBn_frames\fP"
.br
.ti -1c
.RI "   SDL_Texture * \fBtexture\fP"
.br
.ti -1c
.RI "   int \fBframe_pos_x\fP"
.br
.ti -1c
.RI "   int \fBframe_pos_y\fP"
.br
.ti -1c
.RI "   int \fBframe_w\fP"
.br
.ti -1c
.RI "   int \fBframe_h\fP"
.br
.ti -1c
.RI "} \fBtexture_info\fP"
.br
.ti -1c
.RI "\fBInstance::Instance\fP \fBinstances\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Sprite::Factory::frame_h"

.SS "int Sprite::Factory::frame_pos_x"

.SS "int Sprite::Factory::frame_pos_y"

.SS "int Sprite::Factory::frame_w"

.SS "\fBInstance::Instance\fP Sprite::Factory::instances"

.SS "int Sprite::Factory::n_frames"

.SS "SDL_Texture* Sprite::Factory::texture"

.SS "struct { \&.\&.\&. }   Sprite::Factory::texture_info"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
