.TH "Sprite::File" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sprite::File
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBadd\fP (\fBFactory\fP *sprite_database, const char *filename, SDL_Renderer *renderer)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Sprite::File::add (\fBFactory\fP * sprite_database, const char * filename, SDL_Renderer * renderer)"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
