.TH "include/Sprite_data.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Sprite_data.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL2\-2\&.0\&.8/include/SDL\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSprite::Instance::Instance\fP"
.br
.ti -1c
.RI "struct \fBSprite::Factory\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSprite\fP"
.br
.ti -1c
.RI " \fBSprite::Instance\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
