.TH "include/Table_File_core.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Table_File_core.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <omp\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <random>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <cfloat>\fP
.br
\fC#include 'Table_File_data\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTable_File\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTable_File::read\fP (const char *filename, Table_File *t)"
.br
.ti -1c
.RI "void \fBTable_File::clean\fP (Table_File *t)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
