.TH "Table_File" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Table_File
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTable_File\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBread\fP (const char *filename, \fBTable_File\fP *t)"
.br
.ti -1c
.RI "void \fBclean\fP (\fBTable_File\fP *t)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Table_File::clean (\fBTable_File\fP * t)"

.SS "void Table_File::read (const char * filename, \fBTable_File\fP * t)"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
