.TH "Table_File::Table_File" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Table_File::Table_File
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Table_File_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char *** \fBtable\fP"
.br
.ti -1c
.RI "unsigned int \fBnrows\fP"
.br
.ti -1c
.RI "unsigned int * \fBncols\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "unsigned int* Table_File::Table_File::ncols"

.SS "unsigned int Table_File::Table_File::nrows"

.SS "char*** Table_File::Table_File::table"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
