.TH "include/Texture_core.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Texture_core.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL2\-2\&.0\&.8/include/SDL\&.h'\fP
.br
\fC#include 'SDL2\-2\&.0\&.8/include/SDL_image\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTexture\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "SDL_Texture * \fBTexture::load\fP (const char *filename, const SDL_Renderer *renderer)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
