.TH "Tileset" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tileset
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTileset\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (\fBTileset\fP *tileset, const char *filename, const SDL_Renderer *renderer)"
.br
.ti -1c
.RI "void \fBdraw_Single\fP (int tile_row, int tile_col, const \fBTileset\fP *t, int dest_x, int dest_y, int dest_w, int dest_h, const SDL_Renderer *renderer)"
.br
.ti -1c
.RI "void \fBdraw_Grid\fP (const \fBTileset\fP *tileset, const \fBGrid_Camera::Grid_Camera\fP *cam, const \fBGrid::Grid\fP *g, SDL_Renderer *renderer)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Tileset::draw_Grid (const \fBTileset\fP * tileset, const \fBGrid_Camera::Grid_Camera\fP * cam, const \fBGrid::Grid\fP * g, SDL_Renderer * renderer)"

.SS "void Tileset::draw_Single (int tile_row, int tile_col, const \fBTileset\fP * t, int dest_x, int dest_y, int dest_w, int dest_h, const SDL_Renderer * renderer)"

.SS "void Tileset::init (\fBTileset\fP * tileset, const char * filename, const SDL_Renderer * renderer)"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
