.TH "include/Tileset_core.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Tileset_core.h
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include 'Tileset_data\&.h'\fP
.br
\fC#include 'SDL2\-2\&.0\&.8\\include\\SDL\&.h'\fP
.br
\fC#include 'SDL2\-2\&.0\&.8\\include\\SDL_image\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTileset\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTileset::init\fP (Tileset *tileset, const char *filename, const SDL_Renderer *renderer)"
.br
.ti -1c
.RI "void \fBTileset::draw_Single\fP (int tile_row, int tile_col, const Tileset *t, int dest_x, int dest_y, int dest_w, int dest_h, const SDL_Renderer *renderer)"
.br
.ti -1c
.RI "void \fBTileset::draw_Grid\fP (const Tileset *tileset, const \fBGrid_Camera::Grid_Camera\fP *cam, const \fBGrid::Grid\fP *g, SDL_Renderer *renderer)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
