.TH "Tileset::Tileset" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tileset::Tileset
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Tileset_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SDL_Texture * \fBtex\fP"
.br
.ti -1c
.RI "int \fBtile_w\fP"
.br
.ti -1c
.RI "int \fBtile_h\fP"
.br
.ti -1c
.RI "int \fBn_rows\fP"
.br
.ti -1c
.RI "int \fBn_cols\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Tileset::Tileset::n_cols"

.SS "int Tileset::Tileset::n_rows"

.SS "SDL_Texture* Tileset::Tileset::tex"

.SS "int Tileset::Tileset::tile_h"

.SS "int Tileset::Tileset::tile_w"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
