.TH "Vec2D" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vec2D
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVec2D\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBadd\fP (\fBVec2D\fP *a, const \fBVec2D\fP *b)"
.br
.ti -1c
.RI "void \fBsub\fP (\fBVec2D\fP *a, const \fBVec2D\fP *b)"
.br
.ti -1c
.RI "float \fBdot\fP (const \fBVec2D\fP *a, const \fBVec2D\fP *b)"
.br
.ti -1c
.RI "float \fBdist_Squared\fP (const \fBVec2D\fP *a, const \fBVec2D\fP *b)"
.br
.ti -1c
.RI "float \fBmag\fP (const \fBVec2D\fP *a)"
.br
.ti -1c
.RI "float \fBnorm\fP (\fBVec2D\fP *a)"
.br
.ti -1c
.RI "void \fBclip\fP (\fBVec2D\fP *a, float min_x, float max_x, float min_y, float max_y)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Vec2D::add (\fBVec2D\fP * a, const \fBVec2D\fP * b)\fC [inline]\fP"

.SS "void Vec2D::clip (\fBVec2D\fP * a, float min_x, float max_x, float min_y, float max_y)"

.SS "float Vec2D::dist_Squared (const \fBVec2D\fP * a, const \fBVec2D\fP * b)\fC [inline]\fP"

.SS "float Vec2D::dot (const \fBVec2D\fP * a, const \fBVec2D\fP * b)\fC [inline]\fP"

.SS "float Vec2D::mag (const \fBVec2D\fP * a)\fC [inline]\fP"

.SS "float Vec2D::norm (\fBVec2D\fP * a)\fC [inline]\fP"

.SS "void Vec2D::sub (\fBVec2D\fP * a, const \fBVec2D\fP * b)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
