.TH "Vec3D" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vec3D
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVec3D\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBadd\fP (\fBVec3D\fP *a, const \fBVec3D\fP *b)"
.br
.ti -1c
.RI "void \fBsub\fP (\fBVec3D\fP *a, const \fBVec3D\fP *b)"
.br
.ti -1c
.RI "float \fBdot\fP (const \fBVec3D\fP *a, const \fBVec3D\fP *b)"
.br
.ti -1c
.RI "float \fBdist_Squared\fP (const \fBVec3D\fP *a, const \fBVec3D\fP *b)"
.br
.ti -1c
.RI "float \fBmag\fP (const \fBVec3D\fP *a)"
.br
.ti -1c
.RI "float \fBnorm\fP (\fBVec3D\fP *a)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Vec3D::add (\fBVec3D\fP * a, const \fBVec3D\fP * b)\fC [inline]\fP"

.SS "float Vec3D::dist_Squared (const \fBVec3D\fP * a, const \fBVec3D\fP * b)\fC [inline]\fP"

.SS "float Vec3D::dot (const \fBVec3D\fP * a, const \fBVec3D\fP * b)\fC [inline]\fP"

.SS "float Vec3D::mag (const \fBVec3D\fP * a)\fC [inline]\fP"

.SS "float Vec3D::norm (\fBVec3D\fP * a)\fC [inline]\fP"

.SS "void Vec3D::sub (\fBVec3D\fP * a, const \fBVec3D\fP * b)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
