.TH "Vec3D::Vec3D" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vec3D::Vec3D
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Vec_data\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float Vec3D::Vec3D::x"

.SS "float Vec3D::Vec3D::y"

.SS "float Vec3D::Vec3D::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
