.TH "include/Vec_data.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Vec_data.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVec2D::Vec2D\fP"
.br
.ti -1c
.RI "struct \fBVec3D::Vec3D\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBVec2D\fP"
.br
.ti -1c
.RI " \fBVec3D\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
