.TH "include/Vec_core.h" 3 "Sun Oct 28 2018" "tiny2D alpha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Vec_core.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Vec_data\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBVec2D\fP"
.br
.ti -1c
.RI " \fBVec3D\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBVec2D::add\fP (Vec2D *a, const Vec2D *b)"
.br
.ti -1c
.RI "void \fBVec2D::sub\fP (Vec2D *a, const Vec2D *b)"
.br
.ti -1c
.RI "float \fBVec2D::dot\fP (const Vec2D *a, const Vec2D *b)"
.br
.ti -1c
.RI "float \fBVec2D::dist_Squared\fP (const Vec2D *a, const Vec2D *b)"
.br
.ti -1c
.RI "float \fBVec2D::mag\fP (const Vec2D *a)"
.br
.ti -1c
.RI "float \fBVec2D::norm\fP (Vec2D *a)"
.br
.ti -1c
.RI "void \fBVec2D::clip\fP (Vec2D *a, float min_x, float max_x, float min_y, float max_y)"
.br
.ti -1c
.RI "void \fBVec3D::add\fP (Vec3D *a, const Vec3D *b)"
.br
.ti -1c
.RI "void \fBVec3D::sub\fP (Vec3D *a, const Vec3D *b)"
.br
.ti -1c
.RI "float \fBVec3D::dot\fP (const Vec3D *a, const Vec3D *b)"
.br
.ti -1c
.RI "float \fBVec3D::dist_Squared\fP (const Vec3D *a, const Vec3D *b)"
.br
.ti -1c
.RI "float \fBVec3D::mag\fP (const Vec3D *a)"
.br
.ti -1c
.RI "float \fBVec3D::norm\fP (Vec3D *a)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for tiny2D alpha from the source code\&.
